[general]
name = "mra"
version = 1
edition = 5
license = "Apache-2.0"
backends = ["cuda"]

[general.hub]
repo-id = "kernels-community/mra"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/cuda_launch.h",
]

[kernel.mra]
backend = "cuda"
depends = ["torch"]
src = [
    "mra/cuda_kernel.cu",
    "mra/cuda_kernel.h",
    "mra/cuda_launch.cu",
    "mra/cuda_launch.h",
]
