[general]
name = "liger-kernels"
version = 3
edition = 5
license = "BSD-2-Clause"
backends = [
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-community/liger-kernels"

[torch-noarch]

[kernel]
