[general]
name = "flash-attn4"
version = 0
edition = 5
license = "BSD-3-Clause"
backends = ["cuda"]
python-depends = [
    "einops",
    "tvm-ffi",
]

[general.cuda]
minver = "12.8"
python-depends = ["nvidia-cutlass-dsl"]

[general.hub]
repo-id = "kernels-community/flash-attn4"

[torch-noarch]

[kernel]
