[general]
name = "finegrained-fp8"
version = 4
edition = 5
license = "Apache-2.0"
backends = [
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-community/finegrained-fp8"

[torch-noarch]

[kernel]
