[general]
name = "gpt-oss-triton-kernels"
version = 1
edition = 5
license = "MIT"
backends = [
    "cuda",
    "rocm",
    "xpu",
    "cpu",
]

[general.hub]
repo-id = "kernels-community/gpt-oss-triton-kernels"

[torch-noarch]

[kernel]
