[general]
name = "flash-attn-ops"
version = 1
edition = 5
license = "BSD-3-Clause"
backends = [
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-community/flash-attn-ops"

[torch-noarch]

[kernel]
