[general]
name = "aiter-kernels"
version = 2
edition = 5
license = "MIT"
backends = ["rocm"]

[general.hub]
repo-id = "kernels-community/aiter-kernels"

[torch-noarch]
pyext = [
    "py",
    "pyi",
    "json",
]

[kernel]
