[general]
name = "fp8-fbgemm"
version = 1
edition = 5
license = "BSD-3-Clause"
backends = [
    "cuda",
    "rocm",
    "xpu",
]

[general.hub]
repo-id = "kernels-community/fp8-fbgemm"

[torch-noarch]

[kernel]
