[general]
name = "msa"
version = 0
edition = 5
license = "other"
upstream = "https://github.com/MiniMax-AI/MSA"
backends = ["cuda"]
python-depends = ["tvm-ffi"]

[general.cuda]
minver = "12.8"
python-depends = ["nvidia-cutlass-dsl"]

[general.hub]
repo-id = "MiniMaxAI/msa"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.msa]
backend = "cuda"
cuda-capabilities = ["10.0"]
depends = ["torch"]
include = ["torch-ext"]
src = [
    "csrc/build_k2q_csr.cu",
    "csrc/build_decode_schedule.cu",
]
