[general]
name = "flash-attn2"
license = "BSD-3-Clause"
version = 1
backends = [
    "cpu",
    "cuda",
    "xpu",
]


[general.hub]
repo-id = "kernels-community/flash-attn2"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.flash_attn_cpu_avx512]
backend = "cpu"
cxx-flags = [
    "-fopenmp",
    "-mavx512f",
    "-mavx512bf16",
    "-mavx512vl",
    "-mavx512dq",
    "-mavx512bw",
    "-mamx-bf16",
    "-mamx-int8",
    "-mamx-tile",
]
depends = ["torch"]
include = ["flash_attn_cpu"]
src = [
    "flash_attn_cpu/src/fmha_fwd_avx512.cpp",
    "flash_attn_cpu/src/fmha_fwd_avx512.hpp",
    "flash_attn_cpu/src/fmha_fwd_common.hpp",
    "flash_attn_cpu/src/fmha_fwd_kernel.hpp",
]

[kernel.flash_attn_cpu]
backend = "cpu"
cxx-flags = ["-fopenmp"]
depends = ["torch"]
include = ["flash_attn_cpu"]
src = [
    "flash_attn_cpu/flash_api.cpp",
    "flash_attn_cpu/src/fmha_fwd_dispatch.cpp",
    "flash_attn_cpu/src/fmha_fwd_fallback.cpp",
    "flash_attn_cpu/src/fmha_fwd.hpp",
    "flash_attn_cpu/src/fmha_fwd_common.hpp",
    "flash_attn_cpu/src/fmha_fwd_kernel.hpp",
    "flash_attn_cpu/src/fmha_fwd_avx512.hpp",
    "flash_attn_cpu/src/fmha_fwd_fallback.hpp",
    "flash_attn_cpu/src/cpu_features.hpp",
]


[kernel.flash_attn]
backend = "cuda"
cuda-capabilities = [
    "8.0",
    "9.0",
    "10.0",
    "12.0",
]
depends = [
    "torch",
    "cutlass_3_6",
]
src = [
    "flash_attn/flash_api.cpp",
    "flash_attn/src/philox_unpack.cuh",
    "flash_attn/src/namespace_config.h",
    "flash_attn/src/hardware_info.h",
    "flash_attn/src/flash.h",
    "flash_attn/src/static_switch.h",
    "flash_attn/src/alibi.h",
    "flash_attn/src/block_info.h",
    "flash_attn/src/dropout.h",
    "flash_attn/src/kernel_traits.h",
    "flash_attn/src/mask.h",
    "flash_attn/src/philox.cuh",
    "flash_attn/src/rotary.h",
    "flash_attn/src/softmax.h",
    "flash_attn/src/utils.h",
    "flash_attn/src/flash_bwd_hdim128_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim128_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim128_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim128_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim192_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim192_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim192_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim192_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim256_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim256_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim256_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim256_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim32_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim32_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim32_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim32_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim64_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim64_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim64_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim64_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim96_bf16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim96_bf16_sm80.cu",
    "flash_attn/src/flash_bwd_hdim96_fp16_causal_sm80.cu",
    "flash_attn/src/flash_bwd_hdim96_fp16_sm80.cu",
    "flash_attn/src/flash_bwd_kernel.h",
    "flash_attn/src/flash_bwd_launch_template.h",
    "flash_attn/src/flash_bwd_preprocess_kernel.h",
    "flash_attn/src/flash_fwd_hdim128_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim128_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim128_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim128_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim192_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim192_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim192_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim192_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim256_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim256_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim256_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim256_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim32_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim32_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim32_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim32_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim64_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim64_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim64_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim64_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim96_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim96_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_hdim96_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_hdim96_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_kernel.h",
    "flash_attn/src/flash_fwd_launch_template.h",
    "flash_attn/src/flash_fwd_split_hdim128_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim128_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim128_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim128_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim192_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim192_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim192_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim192_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim256_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim256_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim256_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim256_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim32_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim32_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim32_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim32_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim64_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim64_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim64_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim64_fp16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim96_bf16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim96_bf16_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim96_fp16_causal_sm80.cu",
    "flash_attn/src/flash_fwd_split_hdim96_fp16_sm80.cu",
]

[kernel.flash_attn_xpu]
backend = "xpu"
depends = [
    "torch",
    "sycl_tla",
]
src = [
    "flash_attn_xpu/flash_api.cpp",
    "flash_attn_xpu/src/philox.hpp",
    "flash_attn_xpu/src/fmha_fwd_types.hpp",
    "flash_attn_xpu/src/fmha_fwd.hpp",
    "flash_attn_xpu/src/fmha_fwd_impl.hpp",
    "flash_attn_xpu/src/fmha_fwd.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim32_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim64_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim96_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim128_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim160_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim192_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim256_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim512_varlen.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim32_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim64_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim96_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim128_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim160_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim192_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim256_fix.cpp",
    "flash_attn_xpu/src/flash_fwd_hdim512_fix.cpp",
    "flash_attn_xpu/src/fmha_bwd_types.hpp",
    "flash_attn_xpu/src/fmha_bwd.hpp",
    "flash_attn_xpu/src/fmha_bwd_impl.hpp",
    "flash_attn_xpu/src/fmha_bwd.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim32_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim64_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim96_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim128_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim160_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim192_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim256_fix.cpp",
    "flash_attn_xpu/src/flash_bwd_hdim512_fix.cpp",
    "flash_attn_xpu/src/fmha_utils.hpp",
    "flash_attn_xpu/src/collective/fmha_fusion.hpp",
    "flash_attn_xpu/src/collective/copy_block_slm.hpp",
    "flash_attn_xpu/src/collective/fmha_fwd_epilogue.hpp",
    "flash_attn_xpu/src/collective/fmha_fwd_mainloop.hpp",
    "flash_attn_xpu/src/collective/fmha_fwd_scheduler.hpp",
    "flash_attn_xpu/src/kernel/fmha_fwd_kernel.hpp",
    "flash_attn_xpu/src/kernel/fmha_bwd_kernel.hpp",
]
