name: Build PR (macOS)
on:
  pull_request:
    paths-ignore:
      - "**/README.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-kernel:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            max-jobs = 1
            cores = 3
            sandbox = relaxed
      - name: Nix info
        run: nix-shell -p nix-info --run "nix-info -m"
      - uses: cachix/cachix-action@v16
        with:
          name: huggingface
        env:
          USER: runner
      - name: Validate kernel directory
        id: validate
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if KERNEL=$(python3 .github/workflows/validate-kernel-pr.py "pr"); then
            echo "kernel=$KERNEL" >> $GITHUB_OUTPUT
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - name: "Check that repo-id is present"
        if: steps.validate.outputs.skip == 'false'
        run: |
          KERNEL="${{ steps.validate.outputs.kernel }}"
          if ! cat $KERNEL/build.toml | nix run nixpkgs#dasel -- -i toml '$root.general.hub.get("repo-id")' &> /dev/null ; then
            echo "Mandatory repo-id is missing in $KERNEL/build.toml"
            exit 1
          fi
      - name: Install Metal toolchain
        if: steps.validate.outputs.skip == 'false'
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Build kernel
        if: steps.validate.outputs.skip == 'false'
        run: |
          KERNEL="${{ steps.validate.outputs.kernel }}"
          ( cd "$KERNEL" && nix build -L .#ci && ls -l result/ )
